// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_auth.proto

package server

import (
	"context"

	user_auth "zero-rpc-example/buf_proto_example/gen/go/tripo/user_auth/v1"
	"zero-rpc-example/services/user-auth/internal/logic"
	"zero-rpc-example/services/user-auth/internal/svc"
)

type UserAuthServiceServer struct {
	svcCtx *svc.ServiceContext
	user_auth.UnimplementedUserAuthServiceServer
}

func NewUserAuthServiceServer(svcCtx *svc.ServiceContext) *UserAuthServiceServer {
	return &UserAuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserAuthServiceServer) Register(ctx context.Context, in *user_auth.RegisterRequest) (*user_auth.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserAuthServiceServer) Login(ctx context.Context, in *user_auth.LoginRequest) (*user_auth.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserAuthServiceServer) Logout(ctx context.Context, in *user_auth.LogoutRequest) (*user_auth.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserAuthServiceServer) RefreshToken(ctx context.Context, in *user_auth.RefreshTokenRequest) (*user_auth.RefreshTokenResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *UserAuthServiceServer) ChangePassword(ctx context.Context, in *user_auth.ChangePasswordRequest) (*user_auth.ChangePasswordResponse, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *UserAuthServiceServer) ResetPassword(ctx context.Context, in *user_auth.ResetPasswordRequest) (*user_auth.ResetPasswordResponse, error) {
	l := logic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

func (s *UserAuthServiceServer) ConfirmResetPassword(ctx context.Context, in *user_auth.ConfirmResetPasswordRequest) (*user_auth.ConfirmResetPasswordResponse, error) {
	l := logic.NewConfirmResetPasswordLogic(ctx, s.svcCtx)
	return l.ConfirmResetPassword(in)
}

func (s *UserAuthServiceServer) VerifyToken(ctx context.Context, in *user_auth.VerifyTokenRequest) (*user_auth.VerifyTokenResponse, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}
