// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	example "zero-rpc-example/buf_proto_example/gen/go/example/v1"
	"zero-rpc-example/internal/logic"
	"zero-rpc-example/internal/svc"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	example.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *example.GetUserRequest) (*example.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
