// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_auth.proto

package userauthservice

import (
	"context"

	user_auth "zero-rpc-example/buf_proto_example/gen/go/tripo/user_auth/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthToken                    = user_auth.AuthToken
	ChangePasswordRequest        = user_auth.ChangePasswordRequest
	ChangePasswordResponse       = user_auth.ChangePasswordResponse
	ConfirmResetPasswordRequest  = user_auth.ConfirmResetPasswordRequest
	ConfirmResetPasswordResponse = user_auth.ConfirmResetPasswordResponse
	Credentials                  = user_auth.Credentials
	LoginRequest                 = user_auth.LoginRequest
	LoginResponse                = user_auth.LoginResponse
	LogoutRequest                = user_auth.LogoutRequest
	LogoutResponse               = user_auth.LogoutResponse
	RefreshTokenRequest          = user_auth.RefreshTokenRequest
	RefreshTokenResponse         = user_auth.RefreshTokenResponse
	RegisterRequest              = user_auth.RegisterRequest
	RegisterResponse             = user_auth.RegisterResponse
	ResetPasswordRequest         = user_auth.ResetPasswordRequest
	ResetPasswordResponse        = user_auth.ResetPasswordResponse
	VerifyTokenRequest           = user_auth.VerifyTokenRequest
	VerifyTokenResponse          = user_auth.VerifyTokenResponse

	UserAuthService interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
		ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
		ConfirmResetPassword(ctx context.Context, in *ConfirmResetPasswordRequest, opts ...grpc.CallOption) (*ConfirmResetPasswordResponse, error)
		VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	}

	defaultUserAuthService struct {
		cli zrpc.Client
	}
)

func NewUserAuthService(cli zrpc.Client) UserAuthService {
	return &defaultUserAuthService{
		cli: cli,
	}
}

func (m *defaultUserAuthService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserAuthService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserAuthService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUserAuthService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultUserAuthService) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultUserAuthService) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

func (m *defaultUserAuthService) ConfirmResetPassword(ctx context.Context, in *ConfirmResetPasswordRequest, opts ...grpc.CallOption) (*ConfirmResetPasswordResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.ConfirmResetPassword(ctx, in, opts...)
}

func (m *defaultUserAuthService) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	client := user_auth.NewUserAuthServiceClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}
